<?php
    /*
     * Example of using the SDK to embed the HTML code for the playing of a video message  
     *
     * @author Melih Onvural
     */
	require_once 'SDK/TokBoxVideo.php';
        require_once 'Site_Config.php';
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
        <title>TokBox Developer API - Sample Application - Wedding Guest Book</title>
        <link rel="stylesheet" type="text/css" href="style.css" />
</head>
<body>
<div class="disclaimer">
        <b>Note:</b> This is a TokBox API sample application. For more information on the TokBox Developer API please check out:
        <ul>
                <li><a href="http://developers.tokbox.com/">Developer Wiki</a></li>
                <li><a href="http://developers.tokbox.com/index.php/Sample_Applications">More Sample Applications</a></li>
        </ul>
</div>
<div class="container">
        <h1>Coco + Red Bunny's Wedding VideoBook</h1>
	<div class="player">
	<?php
		if(isset($_GET['mid'])) {
			//the HTML code generated by the SDK for the video player
			//Requires a message ID
			$htmlCode = TokBoxVideo::generatePlayerEmbedCode($_GET['mid']);

			echo $htmlCode;
		}
		else {
			echo "I'm sorry, but you're missing a video to play";
		}
	?>
	</div>
	<div class="footermenu">
		<a href="index.php">Back to VideoBook</a>
	</div>
</div>
</body>
</html>
